# Generated by Django 5.2.2 on 2025-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='напишите название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите картинку')),
                ('description', models.TextField(verbose_name='напишите описание книги')),
                ('book_genre', models.CharField(choices=[('Drama', 'Drama'), ('fantasy', 'fantasy'), ('thriller', 'thriller')], max_length=100)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
