# Generated by Django 5.2.2 on 2025-06-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книг'},
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='напишите отзыв')),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('choise_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='книга')),
            ],
        ),
    ]
