# Generated by Django 5.2.2 on 2025-06-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='choise_books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.books', verbose_name='выберите книгу'),
        ),
    ]
